version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  test-unit:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:unit
  test-bdd:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:bdd
workflows:
    test-unit:
      jobs:
        - test-unit
    test-bdd:
      jobs:
        - test-bdd
