version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  install-dependencies:
    working_directory: ~/circleci-auth-service
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
  test-unit:
    working_directory: ~/circleci-auth-service
    executor:
      name: node/default
    steps:
      - run: npm run test:unit
  test-bdd:
    working_directory: ~/circleci-auth-service
    executor:
      name: node/default
    steps:
      - run: npm run test:bdd
workflows:
  version: 2
  build_accept:
    jobs:
      - install-dependencies
      - test-unit:
          requires: 
            - install-dependencies
      - test-bdd:
          requires:
            - install-dependencies