version: 2.1
orbs:
  node: circleci/node@2.1.1
  docker: circleci/docker@1.0.1
jobs:
  setup:
    executor: node/default
    steps:
      - checkout    
      - node/install-packages
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-unit:
    executor: node/default
    steps:
      - checkout    
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm run test:unit
  test-bdd:
    executor: node/default
    steps:
      - checkout    
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: npm run test:bdd
      
  build-docker:
    executor: docker/docker
    steps:
      - checkout
      - docker/install-docker-tools
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          docker build -t $DOCKER_ORG/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG .

workflows:
  version: 2
  build_accept:
    jobs:
      - setup
      - test-unit:
          requires:
            - setup
      - test-bdd:
          requires:
            - setup
      - build-docker:
          requires:
            - test-unit
            - test-bdd