version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build_and_test:
    working_directory: ~/circleci-auth-service
    executor:
      name: node/default
    steps:
      - checkout    
      - node/install-packages
      - run: npm run test:bdd
      - run: npm run test:unit
workflows:
  version: 2
  build_accept:
    jobs:
      - build_and_test