version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  test-unit:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:unit
workflows:
    test-unit:
      jobs:
        - test-unit
