version: 2.1
orbs:
  node: circleci/node@2.1.1
  docker: circleci/docker@1.0.1
jobs:
  setup:
    executor: node/default
    steps:
      - checkout    
      - node/install-packages
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-unit:
    executor: node/default
    steps:
      - checkout    
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: mkdir -p ./test/results-unit
      - run: npm run test:unit
      - run: ls -al ./ 
      - store_artifacts:
          path: ./test/results-unit
          prefix: test
      - store_test_results:
          path: ./test/results-unit
  test-bdd:
    executor: node/default
    steps:
      - checkout    
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run: mkdir -p ./test/results-bdd
      - run: npm run test:bdd
      - run: ls -al ./ 
      - store_artifacts:
          path: ./test/results-bdd
          prefix: test
      - store_test_results:
          path: ./test/results-bdd
      

workflows:
  version: 2
  build_accept:
    jobs:
      - setup
      - test-unit:
          requires:
            - setup
      - test-bdd:
          requires:
            - setup