openapi: 3.0.1
info:
  title: Mojaloop Auth-Service API
  version: '0.1.0'
  description: An API a central auth service in Mojaloop, concerned with creating \nand managing Consents and validating thirdparty transactions
  license:
    name: Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)
servers:
  - url: /
paths:
  /consents:
    $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/consents.yaml'
  /consents/{ID}:
    $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/consents_ID.yaml'
  /health:
    $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/health.yaml'
  /metrics:
    $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/metrics.yaml'
  /thirdpartyRequests/transactions/{ID}/authorizations:
    $ref: '../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/thirdpartyRequests_transactions_ID_authz.yaml'
