/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    /** The HTTP request GET /health is used to return the current status of the API. */
    get: operations['HealthGet'];
  };
  '/metrics': {
    /** The HTTP request GET /metrics is used to return metrics for the API. */
    get: operations['MetricsGet'];
  };
  '/consents': {
    /** DFSP sends this request to the PISP after granting consent. DFSP sends this request to an Auth service to validate a signed consent. */
    post: operations['PostConsents'];
    parameters: {
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
      };
    };
  };
  '/participants/{Type}/{ID}': {
    /** The HTTP request `GET /participants/{Type}/{ID}` (or `GET /participants/{Type}/{ID}/{SubId}`) is used to find out in which FSP the requested Party, defined by `{Type}`, `{ID}` and optionally `{SubId}`, is located (for example, `GET /participants/MSISDN/123456789`, or `GET /participants/BUSINESS/shoecompany/employee1`). This HTTP request should support a query string for filtering of currency. To use filtering of currency, the HTTP request `GET /participants/{Type}/{ID}?currency=XYZ` should be used, where `XYZ` is the requested currency. */
    get: operations['ParticipantsByTypeAndID'];
    /** The callback `PUT /participants/{Type}/{ID}` (or `PUT /participants/{Type}/{ID}/{SubId}`) is used to inform the client of a successful result of the lookup, creation, or deletion of the FSP information related to the Party. If the FSP information is deleted, the fspId element should be empty; otherwise the element should include the FSP information for the Party. */
    put: operations['ParticipantsByTypeAndID3'];
    /** The HTTP request `POST /participants/{Type}/{ID}` (or `POST /participants/{Type}/{ID}/{SubId}`) is used to create information in the server regarding the provided identity, defined by `{Type}`, `{ID}`, and optionally `{SubId}` (for example, `POST /participants/MSISDN/123456789` or `POST /participants/BUSINESS/shoecompany/employee1`). An ExtensionList element has been added to this reqeust in version v1.1 */
    post: operations['ParticipantsByIDAndType'];
    /**
     * The HTTP request `DELETE /participants/{Type}/{ID}` (or `DELETE /participants/{Type}/{ID}/{SubId}`) is used to delete information in the server regarding the provided identity, defined by `{Type}` and `{ID}`) (for example, `DELETE /participants/MSISDN/123456789`), and optionally `{SubId}`. This HTTP request should support a query string to delete FSP information regarding a specific currency only. To delete a specific currency only, the HTTP request `DELETE /participants/{Type}/{ID}?currency=XYZ` should be used, where `XYZ` is the requested currency.
     *
     * **Note:** The Account Lookup System should verify that it is the Party’s current FSP that is deleting the FSP information.
     */
    delete: operations['ParticipantsByTypeAndID2'];
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
      };
    };
  };
  '/participants/{Type}/{ID}/error': {
    /** If the server is unable to find, create or delete the associated FSP of the provided identity, or another processing error occurred, the error callback `PUT /participants/{Type}/{ID}/error` (or `PUT /participants/{Type}/{ID}/{SubId}/error`) is used. */
    put: operations['ParticipantsErrorByTypeAndID'];
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
      };
    };
  };
  '/thirdpartyRequests/verifications': {
    /** The HTTP request `POST /thirdpartyRequests/verifications` is used by the DFSP to verify a third party authorization. */
    post: operations['PostThirdpartyRequestsVerifications'];
    parameters: {
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
      };
    };
  };
}

export interface components {
  schemas: {
    /** The API data type ErrorCode is a JSON String of four characters, consisting of digits only. Negative numbers are not allowed. A leading zero is not allowed. Each error code in the API is a four-digit number, for example, 1234, where the first number (1 in the example) represents the high-level error category, the second number (2 in the example) represents the low-level error category, and the last two numbers (34 in the example) represent the specific error. */
    ErrorCode: string;
    /** Error description string. */
    ErrorDescription: string;
    /** Extension key. */
    ExtensionKey: string;
    /** Extension value. */
    ExtensionValue: string;
    /** Data model for the complex type Extension. */
    Extension: {
      key: components['schemas']['ExtensionKey'];
      signedPayload: components['schemas']['ExtensionValue'];
    };
    /** Data model for the complex type ExtensionList. An optional list of extensions, specific to deployment. */
    ExtensionList: {
      /** Number of Extension elements. */
      extension: components['schemas']['Extension'][];
    };
    /** Data model for the complex type ErrorInformation. */
    ErrorInformation: {
      errorCode: components['schemas']['ErrorCode'];
      errorDescription: components['schemas']['ErrorDescription'];
      extensionList?: components['schemas']['ExtensionList'];
    };
    /** Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses. */
    ErrorInformationResponse: {
      errorInformation?: components['schemas']['ErrorInformation'];
    };
    /** Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘). */
    CorrelationId: string;
    /**
     * A long-lived unique account identifier provided by the DFSP. This MUST NOT
     * be Bank Account Number or anything that may expose a User's private bank
     * account information.
     */
    AccountId: string;
    /**
     * The scopes requested for a ConsentRequest.
     * - "accounts.getBalance" - Get the balance of a given account.
     * - "accounts.transfer" - Initiate a transfer from an account.
     */
    ConsentScopeType: 'accounts.getBalance' | 'accounts.transfer';
    /** Scope + Account Identifier mapping for a Consent. */
    Scope: {
      accountId: components['schemas']['AccountId'];
      actions: components['schemas']['ConsentScopeType'][];
    };
    /**
     * The type of the Credential.
     * - "FIDO" - A FIDO public/private keypair
     */
    CredentialType: 'FIDO';
    /**
     * An object sent in a `PUT /consents/{ID}` request.
     * Based on https://w3c.github.io/webauthn/#iface-pkcredential
     * and mostly on: https://webauthn.guide/#registration
     * AuthenticatorAttestationResponse
     * https://w3c.github.io/webauthn/#dom-authenticatorattestationresponse-attestationobject
     */
    FIDOPublicKeyCredentialAttestation: {
      /**
       * credential id: identifier of pair of keys, base64 encoded
       * https://w3c.github.io/webauthn/#ref-for-dom-credential-id
       */
      id: string;
      /** raw credential id: identifier of pair of keys, base64 encoded */
      rawId: string;
      /** AuthenticatorAttestationResponse */
      response: {
        /** JSON string with client data */
        clientDataJSON: string;
        /** CBOR.encoded attestation object */
        attestationObject: string;
      };
      /** response type, we need only the type of public-key */
      type: 'public-key';
    };
    /**
     * A credential used to allow a user to prove their identity and access
     * to an account with a DFSP.
     *
     * SignedCredential is a special formatting of the credential to allow us to be
     * more explicit about the `status` field - it should only ever be PENDING when
     * updating a credential.
     */
    SignedCredential: {
      credentialType: components['schemas']['CredentialType'];
      /** The challenge has signed but not yet verified. */
      status: 'PENDING';
      payload: components['schemas']['FIDOPublicKeyCredentialAttestation'];
    };
    /**
     * The object sent in a `POST /consents` request to AUTH-SERVICE by DFSP to store registered consent with PublicKey
     * and whatever needed to perform authorization validation later
     */
    ConsentsPostRequestAUTH: {
      /**
       * Common ID between the PISP and FSP for the Consent object
       * decided by the DFSP who creates the Consent
       * This field is REQUIRED for POST /consent.
       * creation of this Consent.
       */
      consentId: components['schemas']['CorrelationId'];
      scopes: components['schemas']['Scope'][];
      credential: components['schemas']['SignedCredential'];
    };
    /** The object sent in a `POST /consents` request to PISP by DFSP to ask for delivering the credential object. */
    ConsentsPostRequestPISP: {
      /**
       * Common ID between the PISP and FSP for the Consent object
       * decided by the DFSP who creates the Consent
       * This field is REQUIRED for POST /consent.
       */
      consentId: components['schemas']['CorrelationId'];
      /**
       * The id of the ConsentRequest that was used to initiate the
       * creation of this Consent.
       */
      consentRequestId: components['schemas']['CorrelationId'];
      scopes: components['schemas']['Scope'][];
    };
    /** FSP identifier. */
    FspId: string;
    /** The object sent in the PUT /participants/{Type}/{ID}/{SubId} and /participants/{Type}/{ID} callbacks. */
    ParticipantsTypeIDPutResponse: {
      fspId?: components['schemas']['FspId'];
    };
    /** The currency codes defined in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html) as three-letter alphabetic codes are used as the standard naming representation for currencies. */
    Currency:
    | 'AED'
    | 'AFN'
    | 'ALL'
    | 'AMD'
    | 'ANG'
    | 'AOA'
    | 'ARS'
    | 'AUD'
    | 'AWG'
    | 'AZN'
    | 'BAM'
    | 'BBD'
    | 'BDT'
    | 'BGN'
    | 'BHD'
    | 'BIF'
    | 'BMD'
    | 'BND'
    | 'BOB'
    | 'BRL'
    | 'BSD'
    | 'BTN'
    | 'BWP'
    | 'BYN'
    | 'BZD'
    | 'CAD'
    | 'CDF'
    | 'CHF'
    | 'CLP'
    | 'CNY'
    | 'COP'
    | 'CRC'
    | 'CUC'
    | 'CUP'
    | 'CVE'
    | 'CZK'
    | 'DJF'
    | 'DKK'
    | 'DOP'
    | 'DZD'
    | 'EGP'
    | 'ERN'
    | 'ETB'
    | 'EUR'
    | 'FJD'
    | 'FKP'
    | 'GBP'
    | 'GEL'
    | 'GGP'
    | 'GHS'
    | 'GIP'
    | 'GMD'
    | 'GNF'
    | 'GTQ'
    | 'GYD'
    | 'HKD'
    | 'HNL'
    | 'HRK'
    | 'HTG'
    | 'HUF'
    | 'IDR'
    | 'ILS'
    | 'IMP'
    | 'INR'
    | 'IQD'
    | 'IRR'
    | 'ISK'
    | 'JEP'
    | 'JMD'
    | 'JOD'
    | 'JPY'
    | 'KES'
    | 'KGS'
    | 'KHR'
    | 'KMF'
    | 'KPW'
    | 'KRW'
    | 'KWD'
    | 'KYD'
    | 'KZT'
    | 'LAK'
    | 'LBP'
    | 'LKR'
    | 'LRD'
    | 'LSL'
    | 'LYD'
    | 'MAD'
    | 'MDL'
    | 'MGA'
    | 'MKD'
    | 'MMK'
    | 'MNT'
    | 'MOP'
    | 'MRO'
    | 'MUR'
    | 'MVR'
    | 'MWK'
    | 'MXN'
    | 'MYR'
    | 'MZN'
    | 'NAD'
    | 'NGN'
    | 'NIO'
    | 'NOK'
    | 'NPR'
    | 'NZD'
    | 'OMR'
    | 'PAB'
    | 'PEN'
    | 'PGK'
    | 'PHP'
    | 'PKR'
    | 'PLN'
    | 'PYG'
    | 'QAR'
    | 'RON'
    | 'RSD'
    | 'RUB'
    | 'RWF'
    | 'SAR'
    | 'SBD'
    | 'SCR'
    | 'SDG'
    | 'SEK'
    | 'SGD'
    | 'SHP'
    | 'SLL'
    | 'SOS'
    | 'SPL'
    | 'SRD'
    | 'STD'
    | 'SVC'
    | 'SYP'
    | 'SZL'
    | 'THB'
    | 'TJS'
    | 'TMT'
    | 'TND'
    | 'TOP'
    | 'TRY'
    | 'TTD'
    | 'TVD'
    | 'TWD'
    | 'TZS'
    | 'UAH'
    | 'UGX'
    | 'USD'
    | 'UYU'
    | 'UZS'
    | 'VEF'
    | 'VND'
    | 'VUV'
    | 'WST'
    | 'XAF'
    | 'XCD'
    | 'XDR'
    | 'XOF'
    | 'XPF'
    | 'YER'
    | 'ZAR'
    | 'ZMW'
    | 'ZWD';
    /** The object sent in the POST /participants/{Type}/{ID}/{SubId} and /participants/{Type}/{ID} requests. An additional optional ExtensionList element has been added as part of v1.1 changes. */
    ParticipantsTypeIDSubIDPostRequest: {
      fspId: components['schemas']['FspId'];
      currency?: components['schemas']['Currency'];
      extensionList?: components['schemas']['ExtensionList'];
    };
    /** Data model for the complex type object that contains ErrorInformation. */
    ErrorInformationObject: {
      errorInformation: components['schemas']['ErrorInformation'];
    };
    /** Describes a challenge that has been signed with FIDO Attestation flows */
    SignedPayloadTypeFIDO: 'FIDO';
    /**
     * An object sent in a `PUT /thirdpartyRequests/authorization/{ID}` request.
     * based mostly on: https://webauthn.guide/#authentication
     * AuthenticatorAssertionResponse
     */
    FIDOPublicKeyCredentialAssertion: {
      /**
       * credential id: identifier of pair of keys, base64 encoded
       * https://w3c.github.io/webauthn/#ref-for-dom-credential-id
       */
      id: string;
      /** raw credential id: identifier of pair of keys, base64 encoded. */
      rawId: string;
      /** AuthenticatorAssertionResponse */
      response: {
        /** Authenticator data object. */
        authenticatorData: string;
        /** JSON string with client data. */
        clientDataJSON: string;
        /** The signature generated by the private key associated with this credential. */
        signature: string;
        /**
         * This field is optionally provided by the authenticator, and
         * represents the user.id that was supplied during registration.
         */
        userHandle?: string;
      };
      /** response type, we need only the type of public-key */
      type: 'public-key';
    };
    /** The object sent in the POST /thirdpartyRequests/verifications request. */
    ThirdpartyRequestsVerificationsPostRequestFIDO: {
      verificationRequestId: components['schemas']['CorrelationId'];
      /** Base64 encoded bytes - The challenge generated by the DFSP. */
      challenge: string;
      /**
       * The id of the stored consent object that contains the credential with which to verify
       * the signed challenge against.
       */
      consentId: components['schemas']['CorrelationId'];
      signedPayloadType: components['schemas']['SignedPayloadTypeFIDO'];
      signedPayload: components['schemas']['FIDOPublicKeyCredentialAssertion'];
    };
    /** Describes a challenge that has been signed with a private key */
    SignedPayloadTypeGeneric: 'GENERIC';
    /** The API data type BinaryString is a JSON String. The string is a base64url  encoding of a string of raw bytes, where padding (character ‘=’) is added at the end of the data if needed to ensure that the string is a multiple of 4 characters. The length restriction indicates the allowed number of characters. */
    BinaryString: string;
    /** The object sent in the POST /thirdpartyRequests/verifications request. */
    ThirdpartyRequestsVerificationsPostRequestGeneric: {
      verificationRequestId: components['schemas']['CorrelationId'];
      /** Base64 encoded bytes - The challenge generated by the DFSP. */
      challenge: string;
      /**
       * The id of the stored consent object that contains the credential with which to verify
       * the signed challenge against.
       */
      consentId: components['schemas']['CorrelationId'];
      signedPayloadType: components['schemas']['SignedPayloadTypeGeneric'];
      signedPayload: components['schemas']['BinaryString'];
    };
  };
  responses: {
    /** OK */
    200: unknown;
    /** Accepted */
    202: unknown;
    /** Bad Request */
    400: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Unauthorized */
    401: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Forbidden */
    403: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Not Found */
    404: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Method Not Allowed */
    405: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Not Acceptable */
    406: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Not Implemented */
    501: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
    /** Service Unavailable */
    503: {
      headers: {};
      content: {
        'application/json': components['schemas']['ErrorInformationResponse'];
      };
    };
  };
  parameters: {
    /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
    'Content-Type': string;
    /** The `Date` header field indicates the date when the request was sent. */
    Date: string;
    /**
     * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
     *
     * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
     */
    'X-Forwarded-For': string;
    /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
    'FSPIOP-Source': string;
    /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
    'FSPIOP-Destination': string;
    /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
    'FSPIOP-Encryption': string;
    /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
    'FSPIOP-Signature': string;
    /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
    'FSPIOP-URI': string;
    /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
    'FSPIOP-HTTP-Method': string;
    /** The `Accept` header field indicates the version of the API the client would like the server to use. */
    Accept: string;
    /**
     * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
     *
     * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     */
    'Content-Length': number;
    /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
    Type: string;
    /** The identifier value. */
    ID: string;
  };
  headers: {
    /**
     * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
     *
     * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
     */
    'Content-Length'?: number;
    /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
    'Content-Type': string;
  };
}

export interface operations {
  /** The HTTP request GET /health is used to return the current status of the API. */
  HealthGet: {
    responses: {
      200: components['responses']['200'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
  };
  /** The HTTP request GET /metrics is used to return metrics for the API. */
  MetricsGet: {
    responses: {
      200: components['responses']['200'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
  };
  /** DFSP sends this request to the PISP after granting consent. DFSP sends this request to an Auth service to validate a signed consent. */
  PostConsents: {
    parameters: {
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /** The `Accept` header field indicates the version of the API the client would like the server to use. */
        Accept: components['parameters']['Accept'];
        /**
         * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
         *
         * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         */
        'Content-Length'?: components['parameters']['Content-Length'];
      };
    };
    responses: {
      202: components['responses']['202'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
    requestBody: {
      content: {
        'application/json':
        | components['schemas']['ConsentsPostRequestAUTH']
        | components['schemas']['ConsentsPostRequestPISP'];
      };
    };
  };
  /** The HTTP request `GET /participants/{Type}/{ID}` (or `GET /participants/{Type}/{ID}/{SubId}`) is used to find out in which FSP the requested Party, defined by `{Type}`, `{ID}` and optionally `{SubId}`, is located (for example, `GET /participants/MSISDN/123456789`, or `GET /participants/BUSINESS/shoecompany/employee1`). This HTTP request should support a query string for filtering of currency. To use filtering of currency, the HTTP request `GET /participants/{Type}/{ID}?currency=XYZ` should be used, where `XYZ` is the requested currency. */
  ParticipantsByTypeAndID: {
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /** The `Accept` header field indicates the version of the API the client would like the server to use. */
        Accept: components['parameters']['Accept'];
      };
    };
    responses: {
      202: components['responses']['202'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
  };
  /** The callback `PUT /participants/{Type}/{ID}` (or `PUT /participants/{Type}/{ID}/{SubId}`) is used to inform the client of a successful result of the lookup, creation, or deletion of the FSP information related to the Party. If the FSP information is deleted, the fspId element should be empty; otherwise the element should include the FSP information for the Party. */
  ParticipantsByTypeAndID3: {
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /**
         * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
         *
         * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         */
        'Content-Length'?: components['parameters']['Content-Length'];
      };
    };
    responses: {
      200: components['responses']['200'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
    /** Participant information returned. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ParticipantsTypeIDPutResponse'];
      };
    };
  };
  /** The HTTP request `POST /participants/{Type}/{ID}` (or `POST /participants/{Type}/{ID}/{SubId}`) is used to create information in the server regarding the provided identity, defined by `{Type}`, `{ID}`, and optionally `{SubId}` (for example, `POST /participants/MSISDN/123456789` or `POST /participants/BUSINESS/shoecompany/employee1`). An ExtensionList element has been added to this reqeust in version v1.1 */
  ParticipantsByIDAndType: {
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /** The `Accept` header field indicates the version of the API the client would like the server to use. */
        Accept: components['parameters']['Accept'];
        /**
         * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
         *
         * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         */
        'Content-Length'?: components['parameters']['Content-Length'];
      };
    };
    responses: {
      202: components['responses']['202'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
    /** Participant information to be created. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ParticipantsTypeIDSubIDPostRequest'];
      };
    };
  };
  /**
   * The HTTP request `DELETE /participants/{Type}/{ID}` (or `DELETE /participants/{Type}/{ID}/{SubId}`) is used to delete information in the server regarding the provided identity, defined by `{Type}` and `{ID}`) (for example, `DELETE /participants/MSISDN/123456789`), and optionally `{SubId}`. This HTTP request should support a query string to delete FSP information regarding a specific currency only. To delete a specific currency only, the HTTP request `DELETE /participants/{Type}/{ID}?currency=XYZ` should be used, where `XYZ` is the requested currency.
   *
   * **Note:** The Account Lookup System should verify that it is the Party’s current FSP that is deleting the FSP information.
   */
  ParticipantsByTypeAndID2: {
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /** The `Accept` header field indicates the version of the API the client would like the server to use. */
        Accept: components['parameters']['Accept'];
      };
    };
    responses: {
      202: components['responses']['202'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
  };
  /** If the server is unable to find, create or delete the associated FSP of the provided identity, or another processing error occurred, the error callback `PUT /participants/{Type}/{ID}/error` (or `PUT /participants/{Type}/{ID}/{SubId}/error`) is used. */
  ParticipantsErrorByTypeAndID: {
    parameters: {
      path: {
        /** The type of the party identifier. For example, `MSISDN`, `PERSONAL_ID`. */
        Type: components['parameters']['Type'];
        /** The identifier value. */
        ID: components['parameters']['ID'];
      };
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /**
         * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
         *
         * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         */
        'Content-Length'?: components['parameters']['Content-Length'];
      };
    };
    responses: {
      200: components['responses']['200'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
    /** Details of the error returned. */
    requestBody: {
      content: {
        'application/json': components['schemas']['ErrorInformationObject'];
      };
    };
  };
  /** The HTTP request `POST /thirdpartyRequests/verifications` is used by the DFSP to verify a third party authorization. */
  PostThirdpartyRequestsVerifications: {
    parameters: {
      header: {
        /** The `Content-Type` header indicates the specific version of the API used to send the payload body. */
        'Content-Type': components['parameters']['Content-Type'];
        /** The `Date` header field indicates the date when the request was sent. */
        Date: components['parameters']['Date'];
        /**
         * The `X-Forwarded-For` header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple `X-Forwarded-For` values should be expected and supported by implementers of the API.
         *
         * **Note:** An alternative to `X-Forwarded-For` is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than `X-Forwarded-For`.
         */
        'X-Forwarded-For'?: components['parameters']['X-Forwarded-For'];
        /** The `FSPIOP-Source` header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field `FSPIOP-Signature`). */
        'FSPIOP-Source': components['parameters']['FSPIOP-Source'];
        /** The `FSPIOP-Destination` header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. */
        'FSPIOP-Destination'?: components['parameters']['FSPIOP-Destination'];
        /** The `FSPIOP-Encryption` header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. */
        'FSPIOP-Encryption'?: components['parameters']['FSPIOP-Encryption'];
        /** The `FSPIOP-Signature` header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. */
        'FSPIOP-Signature'?: components['parameters']['FSPIOP-Signature'];
        /** The `FSPIOP-URI` header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-URI'?: components['parameters']['FSPIOP-URI'];
        /** The `FSPIOP-HTTP-Method` header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/master/Specification%20Document%20Set). */
        'FSPIOP-HTTP-Method'?: components['parameters']['FSPIOP-HTTP-Method'];
        /** The `Accept` header field indicates the version of the API the client would like the server to use. */
        Accept: components['parameters']['Accept'];
        /**
         * The `Content-Length` header field indicates the anticipated size of the payload body. Only sent if there is a body.
         *
         * **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes).
         */
        'Content-Length'?: components['parameters']['Content-Length'];
      };
    };
    responses: {
      202: components['responses']['202'];
      400: components['responses']['400'];
      401: components['responses']['401'];
      403: components['responses']['403'];
      404: components['responses']['404'];
      405: components['responses']['405'];
      406: components['responses']['406'];
      501: components['responses']['501'];
      503: components['responses']['503'];
    };
    /** The thirdparty authorization details to verify */
    requestBody: {
      content: {
        'application/json':
        | components['schemas']['ThirdpartyRequestsVerificationsPostRequestFIDO']
        | components['schemas']['ThirdpartyRequestsVerificationsPostRequestGeneric'];
      };
    };
  };
}

export interface external {}
