Accept:
  name: accept
  description: The Accept header field indicates the version of the API the client would like the server to use.
  in: header
  required: true
  type: string
Content-Length:
  name: content-length
  description: The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body. Note - The API supports a maximum size of 5242880 bytes (5 Megabytes)
  in: header
  required: false
  type: integer
Content-Type:
  name: content-type
  description: The Content-Type header indicates the specific version of the API used to send the payload body.
  in: header
  required: true
  type: string
Date:
  name: date
  description: The Date header field indicates the date when the request was sent.
  in: header
  required: true
  type: string
X-Forwarded-For:
  name: x-forwarded-for
  description: 'The X-Forwarded-For header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple X-Forwarded-For values as in the example shown here should be expected and supported by implementers of the API. Note - An alternative to X-Forwarded-For is defined in RFC 7239. However, to this point RFC 7239 is less-used and supported than X-Forwarded-For.'
  in: header
  required: false
  type: string
FSPIOP-Source:
  name: fspiop-source
  description: The FSPIOP-Source header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field FSPIOP-Signature).
  in: header
  required: true
  type: string
FSPIOP-Destination:
  name: fspiop-destination
  description: 'The FSPIOP-Destination header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field should be set by the original sender of the request (if known), so that any entities between the client and the server do not need to parse the payload for routing purposes.'
  in: header
  required: false
  type: string
FSPIOP-Originator:
  name: fspiop-originator
  description: The FSPIOP-Originator header field is a non-HTTP standard field used by the API for HTTP header based routing and verification of requests originated from PISP participant. The field should be set by the original PISP sender of the request (if known) to clearly identify that PISP is request's originator
  in: header
  required: false
  type: string
FSPIOP-Encryption:
  name: fspiop-encryption
  description: The FSPIOP-Encryption header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.
  in: header
  required: false
  type: string
FSPIOP-Signature:
  name: fspiop-signature
  description: The FSPIOP-Signature header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.
  in: header
  required: false
  type: string
FSPIOP-URI:
  name: fspiop-uri
  description: 'The FSPIOP-URI header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information see API Signature document.'
  in: header
  required: false
  type: string
FSPIOP-HTTP-Method:
  name: fspiop-http-method
  description: 'The FSPIOP-HTTP-Method header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information see API Signature document.'
  in: header
  required: false
  type: string
ID:
  name: ID
  in: path
  required: true
  type: string
Type:
  name: Type
  in: path
  required: true
  type: string
SubId:
  name: SubId
  in: path
  required: true
  type: string